version: "3"
services:
  dashboard:
    image: disitlab/dashboard-builder:v0
    ports:
      - "80:80"
#    volumes:
#      - /home/debian/dashboard-builder/dashboard_frontend:/var/www/html/dashboardSmartCity
#      - /home/debian/snap4city/Ownership-API:/var/www/html/ownership-api
    environment:
      DBB_HOST: "dashboarddb"
      DBB_USER: "user"
      DBB_PASSWORD: "passwordx"
      DBB_APPURL: "http://dashboard/dashboardSmartCity"
      DBB_APPHOST: "dashboard"
      DBB_LDAPACTIVE: "yes"
      DBB_LDAPSERVER: "ldap-server"
      DBB_LDAPPORT: "389"
      DBB_LDAPTOOLNAME: "Dashboard"
      DBB_LDAPBASEDN: "dc=ldap,dc=snap4demo,dc=com"
      DBB_LDAPADMINDN: "cn=admin,dc=ldap,dc=snap4demo,dc=com"
      DBB_LDAPADMINPWD: "secret"
      DBB_SSOCLIENTSECRET: "fd4b64fc-eabd-41e8-aef4-34c9f6864b2c"
      DBB_SSOENDPOINTSFROMURL: "no"
      DBB_SSOENDPOINT: "http://keycloak:8088"
      DBB_SSOAUTHORIZATIONENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/auth"
      DBB_SSOTOKENENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/token"
      DBB_SSOUSERINFOENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      DBB_SSOJWKSURI: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/certs"
      DBB_SSOISSUER: "http://keycloak:8088/auth/realms/master"
      DBB_SSOENDSESSIONENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/logout"
      DBB_OWNERSHIPAPIBASEURL: "http://dashboard/ownership-api"
      DBB_PERSONALDATAAPIBASEURL: "http://personaldata:8080/datamanager/api"
      DBB_WSSERVERADDRESSWIDGETS: "wsserver"
      DBB_WSSERVERPORT: "9000"
      DBB_WSSERVERPROTOCOL: "ws"

      OWN_DB_HOST: "dashboarddb"
      OWN_DB_USER: "user"
      OWN_DB_PWD: "passwordx"
      OWN_SSO_USERINFO_ENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      OWN_LDAPSERVER: "ldap-server"
      OWN_LDAPBASEDN: "dc=ldap,dc=snap4demo,dc=com"
    depends_on:
      - dashboarddb
      - keycloak 
  dashboard-backend:
    image: disitlab/dashboard-backend:v0
    environment:
      url: "jdbc:mysql://dashboarddb:3306"
      database: "Dashboard"
      user: "user"
      psw: "passwordx"
    depends_on: 
      - dashboarddb
  dashboard-cron:
    image: disitlab/dashboard-builder:v0
    volumes:
      - /home/debian/dashboard-builder/dashboard_frontend:/var/www/html/dashboardSmartCity
    environment:
      DBB_HOST: "dashboarddb"
      DBB_USER: "user"
      DBB_PASSWORD: "passwordx"
      DBB_APPURL: "http://dashboard/dashboardSmartCity"
      DBB_APPHOST: "dashboard"
      DBB_LDAPACTIVE: "yes"
      DBB_LDAPSERVER: "ldap-server"
      DBB_LDAPPORT: "389"
      DBB_LDAPTOOLNAME: "Dashboard"
      DBB_LDAPBASEDN: "dc=ldap,dc=snap4demo,dc=com"
      DBB_LDAPADMINDN: "cn=admin,dc=ldap,dc=snap4demo,dc=com"
      DBB_LDAPADMINPWD: "secret"
      DBB_SSOCLIENTSECRET: "fd4b64fc-eabd-41e8-aef4-34c9f6864b2c"
      DBB_SSOENDPOINTSFROMURL: "no"
      DBB_SSOENDPOINT: "http://keycloak:8088"
      DBB_SSOAUTHORIZATIONENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/auth"
      DBB_SSOTOKENENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/token"
      DBB_SSOUSERINFOENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      DBB_SSOJWKSURI: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/certs"
      DBB_SSOISSUER: "http://keycloak:8088/auth/realms/master"
      DBB_SSOENDSESSIONENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/logout"
      DBB_OWNERSHIPAPIBASEURL: "http://dashboard/ownership-api"
      DBB_PERSONALDATAAPIBASEURL: "http://personaldata:8080/datamanager/api"
      DBB_WSSERVERADDRESSWIDGETS: "wsserver"
      DBB_WSSERVERPORT: "9000"
      DBB_WSSERVERPROTOCOL: "ws"

      OWN_DB_HOST: "dashboarddb"
      OWN_DB_USER: "user"
      OWN_DB_PWD: "passwordx"
      OWN_SSO_USERINFO_ENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      OWN_LDAPSERVER: "ldap-server"
      OWN_LDAPBASEDN: "dc=ldap,dc=snap4demo,dc=com"
    command: /bin/sh -c "cd /var/www/html/dashboardSmartCity/ScheduledTasks/; php Personal_Data_FeedDashboardWizard.php"
  personaldata:
    image: disitlab/personaldata:v0
#    image: tomcat:9.0.26-jdk8-openjdk-slim
    volumes:
#      - /home/debian/snap4city/PersonalDataManager/target/datamanager-0.0.1.war:/usr/local/tomcat/webapps/datamanager.war
      - ./datamanager-logs:/datamanager
    environment:
      "spring.profiles.active": "deploy"
      "profiledb.datasource.url": "jdbc:mysql://dashboarddb:3306/profiledb"
      "profiledb.datasource.username": "user"
      "profiledb.datasource.password": "passwordx"
      "spring.openidconnect.userinfo_endpoint": "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      "spring.openidconnect.userinfo_endpoint_test": ""
      "spring.ldap.url": "ldap://ldap-server:389"
      "spring.ldap.basicdn": "dc=ldap,dc=snap4demo,dc=com"
      "spring.ldap.managerdn": "cn=admin,dc=ldap,dc=snap4demo,dc=com"
      "spring.ldap.password": "secret"
      logFileFolder: ""
    ports:
      - 8080:8080
    links:
      - dashboarddb
    depends_on:
      - dashboarddb
      - keycloak 
  wsserver:
    image: disitlab/websocketserver:v0
    ports:
      - 9000:9000
    volumes:
      - ./dashboard-builder-conf:/websocketserver/conf
    depends_on:
      - dashboarddb
      - keycloak 
  iotapp:
    image: disitlab/snap4city-nodered-adv:v45
    volumes:
      - ./iotapp-nr:/data
    ports:
      - "1880:1880"
    depends_on:
      - dashboard
      - keycloak 
  dashboarddb:
    image: mariadb
    volumes:
      - dashboarddb:/var/lib/mysql
      - ./database/dashboard.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database/profiledb.sql:/docker-entrypoint-initdb.d/1_init.sql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwordx'
      MYSQL_DATABASE: 'Dashboard'      
    ports:
      - "3306:3306"
  ldap-server:
    image: disitlab/snap4demo-openldap:v0 
#    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "snap4demo"
      LDAP_DOMAIN: "ldap.snap4demo.com"
      LDAP_ADMIN_PASSWORD: "secret"
    ports:
      - "389:389"
      - "636:636"
  myldap:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
    ports:
      - "6443:443"
    depends_on:
      - "ldap-server"
  keycloak:
      image: disitlab/snap4demo-keycloak:v0 
#      image: jboss/keycloak:4.8.3.Final 
      command: ["-Djboss.socket.binding.port-offset=8"]
      ports:
        - "8088:8088"
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin 
      depends_on:
        - "ldap-server"
volumes:
  dashboarddb:
