version: "3"
services:
  dashboard:
    image: disitlab/dashboard-builder:v1
    ports:
      - "80:80"
    volumes:
       - ./dashboard-builder-conf:/var/www/html/dashboardSmartCity/conf
       - ./notificator-conf:/var/www/html/notificator/conf
       - ./iot-directory-conf:/var/www/html/iot-directory/conf
       - ./iot-directory-certificate:/var/www/certificate
       - ./iot-directory-log:/var/www/log
#      - /home/debian/dashboard-builder/dashboard_frontend:/var/www/html/dashboardSmartCity
#      - /home/debian/snap4city/Ownership-API:/var/www/html/ownership-api
#       - /home/debian/notificator/www:/var/www/html/notificator
    environment:
      OWN_DB_HOST: "dashboarddb"
      OWN_DB_USER: "user"
      OWN_DB_PWD: "passwordx"
      OWN_SSO_USERINFO_ENDPOINT: "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      OWN_LDAPSERVER: "ldap-server"
      OWN_LDAPBASEDN: "dc=ldap,dc=organization,dc=com"
    depends_on:
      - dashboarddb
      - keycloak 
  dashboard-backend:
    image: disitlab/dashboard-backend:v0
    volumes:
      - ./dashboard-backend-conf/config.properties:/usr/app/config.properties
    depends_on: 
      - dashboarddb
  dashboard-cron:
    image: disitlab/dashboard-builder:v0
    volumes:
       - ./dashboard-builder-conf:/var/www/html/dashboardSmartCity/conf
       - ./dashboard-cron-conf/crontab:/etc/cron.d/crontab
 #     - /home/debian/dashboard-builder/dashboard_frontend:/var/www/html/dashboardSmartCity
#    command: /bin/sh -c "cd /var/www/html/dashboardSmartCity/ScheduledTasks/; php Personal_Data_FeedDashboardWizard.php"
    command: /bin/sh -c "cron -f"
  personaldata:
    image: disitlab/personaldata:v0
#    image: tomcat:9.0.26-jdk8-openjdk-slim
    volumes:
      - ./datamanager-logs:/datamanager
    environment:
      "spring.profiles.active": "deploy"
      "profiledb.datasource.url": "jdbc:mysql://dashboarddb:3306/profiledb"
      "profiledb.datasource.username": "user"
      "profiledb.datasource.password": "passwordx"
      "spring.openidconnect.userinfo_endpoint": "http://keycloak:8088/auth/realms/master/protocol/openid-connect/userinfo"
      "spring.openidconnect.userinfo_endpoint_test": ""
      "spring.ldap.url": "ldap://ldap-server:389"
      "spring.ldap.basicdn": "dc=ldap,dc=organization,dc=com"
      "spring.ldap.managerdn": "cn=admin,dc=ldap,dc=organization,dc=com"
      "spring.ldap.password": "secret"
      logFileFolder: ""
    ports:
      - 8080:8080
    links:
      - dashboarddb
    depends_on:
      - dashboarddb
      - keycloak 
  wsserver:
    image: disitlab/websocketserver:v1
    ports:
      - 9000:9000
    volumes:
      - ./dashboard-builder-conf:/websocketserver/conf
    depends_on:
      - dashboarddb
      - keycloak 
  iotapp:
    image: disitlab/snap4city-nodered-adv:v45
    volumes:
      - ./iotapp-nr:/data
    ports:
      - "1880:1880"
    depends_on:
      - dashboard
      - keycloak 
  dashboarddb:
    image: mariadb
    volumes:
      - dashboarddb:/var/lib/mysql
      - ./database/dashboard.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database/profiledb.sql:/docker-entrypoint-initdb.d/1_init.sql
      - ./database/notificator.sql:/docker-entrypoint-initdb.d/2_init.sql
      - ./database/iot-directory.sql:/docker-entrypoint-initdb.d/3_init.sql
    environment:
      TZ: "Europe/Rome"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: "rootpwd"
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'passwordx'
      MYSQL_DATABASE: 'Dashboard'      
    ports:
      - "3306:3306"
  ldap-server:
    image: disitlab/preconf-openldap:v1 
#    image: osixia/openldap
    environment:
      LDAP_ORGANISATION: "organization"
      LDAP_DOMAIN: "ldap.organization.com"
      LDAP_ADMIN_PASSWORD: "secret"
    ports:
      - "389:389"
      - "636:636"
  myldap:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
    ports:
      - "6443:443"
    depends_on:
      - "ldap-server"
  keycloak:
      image: disitlab/preconf-keycloak:v1 
#      image: jboss/keycloak:4.8.3.Final 
      command: ["-Djboss.socket.binding.port-offset=8"]
      ports:
        - "8088:8088"
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin 
      depends_on:
        - ldap-server
volumes:
  dashboarddb:
